name: golang_transformer
author: Sheran Gunasekera <sheran.g@gmail.com>
version: 0.1.10
homepage: https://github.com/sheran/golang_transformer
description: A transformer to swap the HTML FORM action to something else so you can test a different backend while using the Dart Editor
dependencies:
  barback: any
  html5lib: any
